apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-pd-storage-class
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-balanced
volumeBindingMode: WaitForFirstConsumer