# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- if .Values.filestore.remount.enabled}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/{{ .Values.filestore.remount.location }}/{{ .Values.filestore.remount.instanceName }}/{{ .Values.filestore.remount.shareName }}"
    volumeAttributes:
      ip: {{ .Values.filestore.remount.instanceIp }}
      volume: {{ .Values.filestore.remount.sharedName }}
{{- end }}
---